export enum DeskActionTypes {
  DESK_AUTHENTICATION_REQUEST = 'DESK_AUTHENTICATION_REQUEST',
  DESK_AUTHENTICATION_SUCCESS = 'DESK_AUTHENTICATION_SUCCESS',
  DESK_AUTHENTICATION_FAIL = 'DESK_AUTHENTICATION_FAIL',

  FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST',
  FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS',
  FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL',
  FETCH_PROJECT_CANCEL = 'FETCH_PROJECT_CANCEL',

  UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL',
  UPDATE_PROJECT_CANCEL = 'UPDATE_PROJECT_CANCEL',

  INITIALIZE_DATE_FILTERS = 'INITIALIZE_DATE_FILTERS',

  UPDATE_OPERATION_HOURS_REQUEST = 'UPDATE_OPERATION_HOURS_REQUEST',
  UPDATE_OPERATION_HOURS_SUCCESS = 'UPDATE_OPERATION_HOURS_SUCCESS',
  UPDATE_OPERATION_HOURS_FAIL = 'UPDATE_OPERATION_HOURS_FAIL',
  UPDATE_OPERATION_HOURS_CANCEL = 'UPDATE_OPERATION_HOURS_CANCEL',

  FETCH_API_TOKENS_REQUEST = 'FETCH_API_TOKENS_REQUEST',
  FETCH_API_TOKENS_SUCCESS = 'FETCH_API_TOKENS_SUCCESS',
  FETCH_API_TOKENS_FAIL = 'FETCH_API_TOKENS_FAIL',

  CREATE_API_TOKEN_REQUEST = 'CREATE_API_TOKEN_REQUEST',
  CREATE_API_TOKEN_SUCCESS = 'CREATE_API_TOKEN_SUCCESS',
  CREATE_API_TOKEN_FAIL = 'CREATE_API_TOKEN_FAIL',

  DELETE_API_TOKEN_REQUEST = 'DELETE_API_TOKEN_REQUEST',
  DELETE_API_TOKEN_SUCCESS = 'DELETE_API_TOKEN_SUCCESS',
  DELETE_API_TOKEN_FAIL = 'DELETE_API_TOKEN_FAIL',

  SET_API_TOKEN_PAGINATION = 'SET_API_TOKEN_PAGINATION',

  SET_DESK_CONNECTED = 'SET_DESK_CONNECTED',

  SET_DESK_PROJECT = 'SET_DESK_PROJECT',
  SET_DESK_AGENT = 'SET_DESK_AGENT',
  SET_AGENT_CONNECTION = 'SET_AGENT_CONNECTION',

  // macros
  FETCH_MACROS_REQUEST = 'FETCH_MACROS_REQUEST',
  FETCH_MACROS_SUCCESS = 'FETCH_MACROS_SUCCESS',
  FETCH_MACROS_FAIL = 'FETCH_MACROS_FAIL',
  FETCH_MACROS_CANCEL = 'FETCH_MACROS_CANCEL',

  SEARCH_MACROS_REQUEST = 'SEARCH_MACROS_REQUEST',
  SEARCH_MACROS_SUCCESS = 'SEARCH_MACROS_SUCCESS',
  SEARCH_MACROS_FAIL = 'SEARCH_MACROS_FAIL',
  SEARCH_MACROS_CANCEL = 'SEARCH_MACROS_CANCEL',

  SET_MACROS_PAGINATION = 'SET_MACROS_PAGINATION',

  ADD_MACROS_REQUEST = 'ADD_MACROS_REQUEST',
  ADD_MACROS_SUCCESS = 'ADD_MACROS_SUCCESS',
  ADD_MACROS_FAIL = 'ADD_MACROS_FAIL',
  ADD_MACROS_CANCEL = 'ADD_MACROS_CANCEL',

  EDIT_MACROS_REQUEST = 'EDIT_MACROS_REQUEST',
  EDIT_MACROS_SUCCESS = 'EDIT_MACROS_SUCCESS',
  EDIT_MACROS_FAIL = 'EDIT_MACROS_FAIL',
  EDIT_MACROS_CANCEL = 'EDIT_MACROS_CANCEL',

  DELETE_MACROS_REQUEST = 'DELETE_MACROS_REQUEST',
  DELETE_MACROS_SUCCESS = 'DELETE_MACROS_SUCCESS',
  DELETE_MACROS_FAIL = 'DELETE_MACROS_FAIL',
  DELETE_MACROS_CANCEL = 'DELETE_MACROS_CANCEL',

  SET_MACRO_SHOW = 'SET_MACRO_SHOW',
  SET_MACRO_CONFIRM_SHOW = 'SET_MACRO_CONFIRM_SHOW',
  SET_ACTIVE_MACRO = 'SET_ACTIVE_MACRO',

  RESET_DESK = 'RESET_DESK',
}

export enum TicketsActionTypes {
  FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST',
  FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS',
  FETCH_TICKETS_FAIL = 'FETCH_TICKETS_FAIL',
  FETCH_TICKETS_CANCEL = 'FETCH_TICKETS_CANCEL',
  RESET_TICKETS_SEARCH = 'RESET_TICKETS_SEARCH',

  CLOSE_TICKET_REQUEST = 'CLOSE_TICKET_REQUEST',
  CLOSE_TICKET_SUCCESS = 'CLOSE_TICKET_SUCCESS',
  CLOSE_TICKET_FAIL = 'CLOSE_TICKET_FAIL',
  CLOSE_TICKET_CANCEL = 'CLOSE_TICKET_CANCEL',

  FORCE_ASSIGN_TICKET_REQUEST = 'FORCE_ASSIGN_TICKET_REQUEST',
  FORCE_ASSIGN_TICKET_SUCCESS = 'FORCE_ASSIGN_TICKET_SUCCESS',
  FORCE_ASSIGN_TICKET_FAIL = 'FORCE_ASSIGN_TICKET_FAIL',
  FORCE_ASSIGN_TICKET_CANCEL = 'FORCE_ASSIGN_TICKET_CANCEL',

  TRANSFER_TICKET_REQUEST = 'TRANSFER_TICKET_REQUEST',
  TRANSFER_TICKET_SUCCESS = 'TRANSFER_TICKET_SUCCESS',
  TRANSFER_TICKET_FAIL = 'TRANSFER_TICKET_FAIL',
  TRANSFER_TICKET_CANCEL = 'TRANSFER_TICKET_CANCEL',

  REOPEN_TICKET_REQUEST = 'REOPEN_TICKET_REQUEST',
  REOPEN_TICKET_SUCCESS = 'REOPEN_TICKET_SUCCESS',
  REOPEN_TICKET_FAIL = 'REOPEN_TICKET_FAIL',
  REOPEN_TICKET_CANCEL = 'REOPEN_TICKET_CANCEL',

  ASSIGN_TICKET_TO_AGENT_GROUP_REQUEST = 'ASSIGN_TICKET_TO_AGENT_GROUP_REQUEST',
  ASSIGN_TICKET_TO_AGENT_GROUP_SUCCESS = 'ASSIGN_TICKET_TO_AGENT_GROUP_SUCCESS',
  ASSIGN_TICKET_TO_AGENT_GROUP_FAIL = 'ASSIGN_TICKET_TO_AGENT_GROUP_FAIL',
  ASSIGN_TICKET_TO_AGENT_GROUP_CANCEL = 'ASSIGN_TICKET_TO_AGENT_GROUP_CANCEL',

  SET_TICKETS_SEARCH_ON = 'SET_TICKETS_SEARCH_ON',
  SET_TICKETS_SEARCH_OFF = 'SET_TICKETS_SEARCH_OFF',
  SET_TICKETS_SEARCH_TOGGLE = 'SET_TICKETS_SEARCH_TOGGLE',

  SET_TICKETS_SEARCH_QUERY = 'SET_TICKETS_SEARCH_QUERY',
  SET_TICKETS_SEARCH_SAVED_PARAMETERS = 'SET_TICKETS_SEARCH_SAVED_PARAMETERS',

  SET_TICKETS_REFRESH_AUTOMATIC = 'SET_TICKETS_REFRESH_AUTOMATIC',
  SET_TICKETS_REFRESH_AUTOMATIC_ITEM = 'SET_TICKETS_REFRESH_AUTOMATIC_ITEM',

  MOVE_TICKET_TO_WIP_REQUEST = 'MOVE_TICKET_TO_WIP_REQUEST',
  MOVE_TICKET_TO_WIP_SUCCESS = 'MOVE_TICKET_TO_WIP_SUCCESS',
  MOVE_TICKET_TO_WIP_FAIL = 'MOVE_TICKET_TO_WIP_FAIL',

  MOVE_TICKET_TO_IDLE_REQUEST = 'MOVE_TICKET_TO_IDLE_REQUEST',
  MOVE_TICKET_TO_IDLE_SUCCESS = 'MOVE_TICKET_TO_IDLE_SUCCESS',
  MOVE_TICKET_TO_IDLE_FAIL = 'MOVE_TICKET_TO_IDLE_FAIL',

  UPDATE_TICKETS_ITEM = 'UPDATE_TICKETS_ITEM',
}

export enum ConversationActionTypes {
  RESET_CONVERSATION = 'RESET_CONVERSATION',
  RESET_CONVERSATION_MESSAGES = 'RESET_CONVERSATION_MESSAGES',
  RECEIVE_CONVERSATION_TICKET_ASSIGNMENT = 'RECEIVE_CONVERSATION_TICKET_ASSIGNMENT',

  FETCH_CONVERSATION_REQUEST = 'FETCH_CONVERSATION_REQUEST',
  FETCH_CONVERSATION_SUCCESS = 'FETCH_CONVERSATION_SUCCESS',
  FETCH_CONVERSATION_FAIL = 'FETCH_CONVERSATION_FAIL',
  FETCH_CONVERSATION_CANCEL = 'FETCH_CONVERSATION_CANCEL',

  FETCH_CONVERSATION_MESSAGES_REQUEST = 'FETCH_CONVERSATION_MESSAGES_REQUEST',
  FETCH_CONVERSATION_MESSAGES_SUCCESS = 'FETCH_CONVERSATION_MESSAGES_SUCCESS',
  FETCH_CONVERSATION_MESSAGES_FAIL = 'FETCH_CONVERSATION_MESSAGES_FAIL',
  FETCH_CONVERSATION_MESSAGES_CANCEL = 'FETCH_CONVERSATION_MESSAGES_CANCEL',

  UPDATE_CONVERSATION_TICKET_MESSAGE = 'UPDATE_CONVERSATION_TICKET_MESSAGE',

  UPDATE_CONVERSATION_TICKET_FILTER = 'UPDATE_CONVERSATION_TICKET_FILTER',

  UPDATE_CONVERSATION_TICKET_ASSIGNMENT_REQUEST = 'UPDATE_CONVERSATION_TICKET_ASSIGNMENT_REQUEST',

  SET_CONVERSATION_ASSIGNMENT = 'SET_CONVERSATION_ASSIGNMENT',

  // URL Preview
  FETCH_URL_PREVIEW_REQUEST = 'FETCH_URL_PREVIEW_REQUEST',
  FETCH_URL_PREVIEW_SUCCESS = 'FETCH_URL_PREVIEW_SUCCESS',
  FETCH_URL_PREVIEW_FAIL = 'FETCH_URL_PREVIEW_FAIL',

  // assign myself
  ASSIGN_TICKET_TO_MYSELF_REQUEST = 'ASSIGN_TICKET_TO_MYSELF_REQUEST',
  ASSIGN_TICKET_TO_MYSELF_SUCCESS = 'ASSIGN_TICKET_TO_MYSELF_SUCCESS',
  ASSIGN_TICKET_TO_MYSELF_FAIL = 'ASSIGN_TICKET_TO_MYSELF_FAIL',

  SET_TYPING_STATUS = 'SET_TYPING_STATUS',
  SET_AGENT_TYPING_STATUS = 'SET_AGENT_TYPING_STATUS',
  SET_OTHERS_TYPING_STATUS = 'SET_OTHERS_TYPING_STATUS',

  // Facebook
  FETCH_FACEBOOK_MESSAGES_REQUEST = 'FETCH_FACEBOOK_MESSAGES_REQUEST',
  FETCH_FACEBOOK_MESSAGES_SUCCESS = 'FETCH_FACEBOOK_MESSAGES_SUCCESS',
  FETCH_FACEBOOK_MESSAGES_FAIL = 'FETCH_FACEBOOK_MESSAGES_FAIL',
  FETCH_FACEBOOK_MESSAGES_CANCEL = 'FETCH_FACEBOOK_MESSAGES_CANCEL',

  // single
  UPDATE_FACEBOOK_MESSAGE_REQUEST = 'UPDATE_FACEBOOK_MESSAGE_REQUEST',

  SEND_FACEBOOK_MESSAGE_REQUEST = 'SEND_FACEBOOK_MESSAGE_REQUEST',
  SEND_FACEBOOK_MESSAGE_SUCCESS = 'SEND_FACEBOOK_MESSAGE_SUCCESS',
  SEND_FACEBOOK_MESSAGE_FAIL = 'SEND_FACEBOOK_MESSAGE_FAIL',

  FETCH_FACEBOOK_FEEDS_REQUEST = 'FETCH_FACEBOOK_FEEDS_REQUEST',
  FETCH_FACEBOOK_FEEDS_SUCCESS = 'FETCH_FACEBOOK_FEEDS_SUCCESS',
  FETCH_FACEBOOK_FEEDS_FAIL = 'FETCH_FACEBOOK_FEEDS_FAIL',
  FETCH_FACEBOOK_FEEDS_CANCEL = 'FETCH_FACEBOOK_FEEDS_CANCEL',

  CREATE_FACEBOOK_FEED_REQUEST = 'CREATE_FACEBOOK_FEED_REQUEST',

  EDIT_FACEBOOK_FEED_REQUEST = 'EDIT_FACEBOOK_FEED_REQUEST',
  EDIT_FACEBOOK_FEED_SUCCESS = 'EDIT_FACEBOOK_FEED_SUCCESS',
  EDIT_FACEBOOK_FEED_FAIL = 'EDIT_FACEBOOK_FEED_FAIL',

  DELETE_FACEBOOK_FEED_REQUEST = 'DELETE_FACEBOOK_FEED_REQUEST',
  DELETE_FACEBOOK_FEED_SUCCESS = 'DELETE_FACEBOOK_FEED_SUCCESS',
  DELETE_FACEBOOK_FEED_FAIL = 'DELETE_FACEBOOK_FEED_FAIL',

  // instagram
  FETCH_INSTAGRAM_COMMENTS_REQUEST = 'FETCH_INSTAGRAM_COMMENTS_REQUEST',
  FETCH_INSTAGRAM_COMMENTS_SUCCESS = 'FETCH_INSTAGRAM_COMMENTS_SUCCESS',
  FETCH_INSTAGRAM_COMMENTS_FAIL = 'FETCH_INSTAGRAM_COMMENTS_FAIL',

  CREATE_INSTAGRAM_COMMENT_REQUEST = 'CREATE_INSTAGRAM_COMMENT_REQUEST',
  CREATE_INSTAGRAM_COMMENT_SUCCESS = 'CREATE_INSTAGRAM_COMMENT_SUCCESS',
  CREATE_INSTAGRAM_COMMENT_FAIL = 'CREATE_INSTAGRAM_COMMENT_FAIL',

  UPDATE_INSTAGRAM_COMMENT_SUCCESS = 'UPDATE_INSTAGRAM_COMMENT_SUCCESS',
  UPDATE_INSTAGRAM_COMMENT_FAIL = 'UPDATE_INSTAGRAM_COMMENT_FAIL',

  UPDATE_INSTAGRAM_COMMENT_FROM_DESK_EVENT = 'UPDATE_INSTAGRAM_COMMENT_FROM_DESK_EVENT',

  DELETE_INSTAGRAM_COMMENT_REQUEST = 'DELETE_INSTAGRAM_COMMENT_REQUEST',
  DELETE_INSTAGRAM_COMMENT_SUCCESS = 'DELETE_INSTAGRAM_COMMENT_SUCCESS',
  DELETE_INSTAGRAM_COMMENT_FAIL = 'DELETE_INSTAGRAM_COMMENT_FAIL',

  // whatsapp
  FETCH_WHATSAPP_MESSAGES_REQUEST = 'FETCH_WHATSAPP_MESSAGES_REQUEST',
  FETCH_WHATSAPP_MESSAGES_SUCCESS = 'FETCH_WHATSAPP_MESSAGES_SUCCESS',
  FETCH_WHATSAPP_MESSAGES_FAIL = 'FETCH_WHATSAPP_MESSAGES_FAIL',

  CREATE_WHATSAPP_MESSAGE_REQUEST = 'CREATE_WHATSAPP_MESSAGE_REQUEST',
  CREATE_WHATSAPP_MESSAGE_SUCCESS = 'CREATE_WHATSAPP_MESSAGE_SUCCESS',
  CREATE_WHATSAPP_MESSAGE_FAIL = 'CREATE_WHATSAPP_MESSAGE_FAIL',

  UPDATE_WHATSAPP_MESSAGE_FROM_DESK_EVENT = 'UPDATE_WHATSAPP_MESSAGE_FROM_DESK_EVENT',

  // multiple
  UPDATE_FACEBOOK_FEEDS_REQUEST = 'UPDATE_FACEBOOK_FEEDS_REQUEST',

  // single
  UPDATE_FACEBOOK_FEED_REQUEST = 'UPDATE_FACEBOOK_FEED_REQUEST',

  FACEBOOK_FEED_LIKE_REQUEST = 'FACEBOOK_FEED_LIKE_REQUEST',
  FACEBOOK_FEED_LIKE_SUCCESS = 'FACEBOOK_FEED_LIKE_SUCCESS',
  FACEBOOK_FEED_LIKE_FAIL = 'FACEBOOK_FEED_LIKE_FAIL',

  FACEBOOK_FEED_UNLIKE_REQUEST = 'FACEBOOK_FEED_UNLIKE_REQUEST',
  FACEBOOK_FEED_UNLIKE_SUCCESS = 'FACEBOOK_FEED_UNLIKE_SUCCESS',
  FACEBOOK_FEED_UNLIKE_FAIL = 'FACEBOOK_FEED_UNLIKE_FAIL',

  MARK_AS_READ_REQUEST = 'MARK_AS_READ_REQUEST',
  MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS',
  MARK_AS_READ_FAIL = 'MARK_AS_READ_FAIL',

  // twitter

  FETCH_TWITTER_DIRECT_MESSAGES_REQUEST = 'FETCH_TWITTER_DIRECT_MESSAGES_REQUEST',
  FETCH_TWITTER_DIRECT_MESSAGES_SUCCESS = 'FETCH_TWITTER_DIRECT_MESSAGES_SUCCESS',
  FETCH_TWITTER_DIRECT_MESSAGES_FAIL = 'FETCH_TWITTER_DIRECT_MESSAGES_FAIL',

  CREATE_TWITTER_DIRECT_MESSAGE_EVENT_REQUEST = 'CREATE_TWITTER_DIRECT_MESSAGE_EVENT_REQUEST',
  CREATE_TWITTER_DIRECT_MESSAGE_EVENT_SUCCESS = 'CREATE_TWITTER_DIRECT_MESSAGE_EVENT_SUCCESS',
  CREATE_TWITTER_DIRECT_MESSAGE_EVENT_FAIL = 'CREATE_TWITTER_DIRECT_MESSAGE_EVENT_FAIL',

  UPSERT_TWITTER_DIRECT_MESSAGE_EVENT = 'UPSERT_TWITTER_DIRECT_MESSAGE_EVENT',

  DELETE_TWITTER_DIRECT_MESSAGE_EVENT_REQUEST = 'DELETE_TWITTER_DIRECT_MESSAGE_EVENT_REQUEST',
  DELETE_TWITTER_DIRECT_MESSAGE_EVENT_SUCCESS = 'DELETE_TWITTER_DIRECT_MESSAGE_EVENT_SUCCESS',
  DELETE_TWITTER_DIRECT_MESSAGE_EVENT_FAIL = 'DELETE_TWITTER_DIRECT_MESSAGE_EVENT_FAIL',

  FETCH_TWITTER_STATUSES_REQUEST = 'FETCH_TWITTER_STATUSES_REQUEST',
  FETCH_TWITTER_STATUSES_SUCCESS = 'FETCH_TWITTER_STATUSES_SUCCESS',
  FETCH_TWITTER_STATUSES_FAIL = 'FETCH_TWITTER_STATUSES_FAIL',

  CREATE_TWITTER_STATUS_REQUEST = 'CREATE_TWITTER_STATUS_REQUEST',
  CREATE_TWITTER_STATUS_SUCCESS = 'CREATE_TWITTER_STATUS_SUCCESS',
  CREATE_TWITTER_STATUS_FAIL = 'CREATE_TWITTER_STATUS_FAIL',

  PATCH_TWITTER_STATUS_REQUEST = 'PATCH_TWITTER_STATUS_REQUEST',
  PATCH_TWITTER_STATUS_SUCCESS = 'PATCH_TWITTER_STATUS_SUCCESS',
  PATCH_TWITTER_STATUS_FAIL = 'PATCH_TWITTER_STATUS_FAIL',

  PATCH_TWITTER_STATUS_TWITTER_USER_REQUEST = 'PATCH_TWITTER_STATUS_TWITTER_USER_REQUEST',
  PATCH_TWITTER_STATUS_TWITTER_USER_SUCCESS = 'PATCH_TWITTER_STATUS_TWITTER_USER_SUCCESS',
  PATCH_TWITTER_STATUS_TWITTER_USER_FAIL = 'PATCH_TWITTER_STATUS_TWITTER_USER_FAIL',

  UPDATE_TWITTER_STATUS_FROM_DESK_EVENT = 'UPDATE_TWITTER_STATUS_FROM_DESK_EVENT',
}

export enum TicketDetailActionTypes {
  FETCH_TICKET_DETAIL_TICKET_REQUEST = 'FETCH_TICKET_DETAIL_TICKET_REQUEST',
  FETCH_TICKET_DETAIL_TICKET_SUCCESS = 'FETCH_TICKET_DETAIL_TICKET_SUCCESS',
  FETCH_TICKET_DETAIL_TICKET_FAIL = 'FETCH_TICKET_DETAIL_TICKET_FAIL',
  FETCH_TICKET_DETAIL_TICKET_CANCEL = 'FETCH_TICKET_DETAIL_TICKET_CANCEL',

  FETCH_TICKET_DETAIL_HEADER_REQUEST = 'FETCH_TICKET_DETAIL_HEADER_REQUEST',
  FETCH_TICKET_DETAIL_HEADER_SUCCESS = 'FETCH_TICKET_DETAIL_HEADER_SUCCESS',
  FETCH_TICKET_DETAIL_HEADER_FAIL = 'FETCH_TICKET_DETAIL_HEADER_FAIL',
  FETCH_TICKET_DETAIL_HEADER_CANCEL = 'FETCH_TICKET_DETAIL_HEADER_CANCEL',

  FETCH_TICKET_DETAIL_MESSAGES_REQUEST = 'FETCH_TICKET_DETAIL_MESSAGES_REQUEST',
  FETCH_TICKET_DETAIL_MESSAGES_SUCCESS = 'FETCH_TICKET_DETAIL_MESSAGES_SUCCESS',
  FETCH_TICKET_DETAIL_MESSAGES_FAIL = 'FETCH_TICKET_DETAIL_MESSAGES_FAIL',
  FETCH_TICKET_DETAIL_MESSAGES_CANCEL = 'FETCH_TICKET_DETAIL_MESSAGES_CANCEL',

  UPDATE_TICKET_DETAIL_SENDBIRD_API_MESSAGE = 'UPDATE_TICKET_DETAIL_SENDBIRD_API_MESSAGE',

  RESET_TICKET_DETAIL = 'RESET_TICKET_DETAIL',
  UPDATE_TICKET_DETAIL = 'UPDATE_TICKET_DETAIL',
}

export enum TicketHistoryActionTypes {
  SET_TICKET_HISTORY_CURRENT = 'SET_TICKET_HISTORY_CURRENT',

  FETCH_TICKET_HISTORY_MESSAGES_REQUEST = 'FETCH_TICKET_HISTORY_MESSAGES_REQUEST',
  FETCH_TICKET_HISTORY_MESSAGES_SUCCESS = 'FETCH_TICKET_HISTORY_MESSAGES_SUCCESS',
  FETCH_TICKET_HISTORY_MESSAGES_FAIL = 'FETCH_TICKET_HISTORY_MESSAGES_FAIL',
  FETCH_TICKET_HISTORY_MESSAGES_CANCEL = 'FETCH_TICKET_HISTORY_MESSAGES_CANCEL',

  RESET_TICKET_HISTORY = 'RESET_TICKET_HISTORY',
  RESET_TICKET_HISTORY_CURRENT = 'RESET_TICKET_HISTORY_CURRENT',
}

export enum ConfigurationsActionTypes {
  SET_DESKTOP_NOTIFICATION_GRANTED = 'SET_DESKTOP_NOTIFICATION_GRANTED',
}

export enum AgentGroupActionTypes {
  FETCH_AGENT_GROUPS_REQUEST = 'FETCH_AGENT_GROUPS_REQUEST',
  FETCH_AGENT_GROUPS_SUCCESS = 'FETCH_AGENT_GROUPS_SUCCESS',
  FETCH_AGENT_GROUPS_FAIL = 'FETCH_AGENT_GROUPS_FAIL',

  RESET_AGENT_GROUPS = 'RESET_AGENT_GROUPS',

  FETCH_AGENT_GROUP_REQUEST = 'FETCH_AGENT_GROUP_REQUEST',
  FETCH_AGENT_GROUP_SUCCESS = 'FETCH_AGENT_GROUP_SUCCESS',
  FETCH_AGENT_GROUP_FAIL = 'FETCH_AGENT_GROUP_FAIL',

  FETCH_CURRENT_AGENTS_REQUEST = 'FETCH_CURRENT_AGENTS_REQUEST',
  FETCH_CURRENT_AGENTS_SUCCESS = 'FETCH_CURRENT_AGENTS_SUCCESS',
  FETCH_CURRENT_AGENTS_FAIL = 'FETCH_CURRENT_AGENTS_FAIL',

  CREATE_AGENT_GROUP_REQUEST = 'CREATE_AGENT_GROUP_REQUEST',
  CREATE_AGENT_GROUP_SUCCESS = 'CREATE_AGENT_GROUP_SUCCESS',
  CREATE_AGENT_GROUP_FAIL = 'CREATE_AGENT_GROUP_FAIL',

  UPDATE_AGENT_GROUP_REQUEST = 'UPDATE_AGENT_GROUP_REQUEST',
  UPDATE_AGENT_GROUP_SUCCESS = 'UPDATE_AGENT_GROUP_SUCCESS',
  UPDATE_AGENT_GROUP_FAIL = 'UPDATE_AGENT_GROUP_FAIL',

  UPDATE_AGENT_GROUP_MEMBERS = 'UPDATE_AGENT_GROUP_MEMBERS',
  UPDATE_AGENT_GROUP_QUERY = 'UPDATE_AGENT_GROUP_QUERY',
  UPDATE_CURRENT_AGENT_SEARCH_QUERY = 'UPDATE_CURRENT_AGENT_SEARCH_QUERY',

  DELETE_AGENT_GROUP_REQUEST = 'DELETE_AGENT_GROUP_REQUEST',
  DELETE_AGENT_GROUP_SUCCESS = 'DELETE_AGENT_GROUP_SUCCESS',
  DELETE_AGENT_GROUP_FAIL = 'DELETE_AGENT_GROUP_FAIL',

  RESET_AGENT_GROUP_FORM_ITEM = 'RESET_AGENT_GROUP_FORM_ITEM',
}

export enum CustomersActionTypes {
  FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL',
  FETCH_CUSTOMERS_CANCEL = 'FETCH_CUSTOMERS_CANCEL',

  FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST',
  FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS',
  FETCH_CUSTOMER_FAIL = 'FETCH_CUSTOMER_FAIL',
  FETCH_CUSTOMER_CANCEL = 'FETCH_CUSTOMER_CANCEL',

  FETCH_CUSTOMER_TICKETS_REQUEST = 'FETCH_CUSTOMER_TICKETS_REQUEST',
  FETCH_CUSTOMER_TICKETS_SUCCESS = 'FETCH_CUSTOMER_TICKETS_SUCCESS',
  FETCH_CUSTOMER_TICKETS_FAIL = 'FETCH_CUSTOMER_TICKETS_FAIL',
  FETCH_CUSTOMER_TICKETS_CANCEL = 'FETCH_CUSTOMER_TICKETS_CANCEL',

  SET_CUSTOMERS_SEARCH_QUERY = 'SET_CUSTOMERS_SEARCH_QUERY',

  SET_CUSTOMERS_PAGINATION = 'SET_CUSTOMERS_PAGINATION',
  SET_CUSTOMER_TICKETS_PAGINATION = 'SET_CUSTOMERS_TICKETS_PAGINATION',
}

export enum MonitorActionTypes {
  FETCH_MONITOR_METRIC_REQUEST = 'FETCH_MONITOR_METRIC_REQUEST',
  FETCH_MONITOR_METRIC_SUCCESS = 'FETCH_MONITOR_METRIC_SUCCESS',
  FETCH_MONITOR_METRIC_FAIL = 'FETCH_MONITOR_METRIC_FAIL',
  FETCH_MONITOR_METRIC_CANCEL = 'FETCH_MONITOR_METRIC_CANCEL',
}

export enum IntegrationsActionTypes {
  FACEBOOK_LOAD_PAGES_REQUEST = 'FACEBOOK_LOAD_PAGES_REQUEST',
  FACEBOOK_LOAD_PAGES_SUCCESS = 'FACEBOOK_LOAD_PAGES_SUCCESS',
  FACEBOOK_LOAD_PAGES_FAIL = 'FACEBOOK_LOAD_PAGES_FAIL',
  FACEBOOK_LOAD_PAGES_CANCEL = 'FACEBOOK_LOAD_PAGES_CANCEL',

  FACEBOOK_ADD_PAGES_REQUEST = 'FACEBOOK_ADD_PAGES_REQUEST',
  FACEBOOK_ADD_PAGES_SUCCESS = 'FACEBOOK_ADD_PAGES_SUCCESS',
  FACEBOOK_ADD_PAGES_FAIL = 'FACEBOOK_ADD_PAGES_FAIL',

  FACEBOOK_SUBSCRIBE_REQUEST = 'FACEBOOK_SUBSCRIBE_REQUEST',
  FACEBOOK_SUBSCRIBE_SUCCESS = 'FACEBOOK_SUBSCRIBE_SUCCESS',
  FACEBOOK_SUBSCRIBE_FAIL = 'FACEBOOK_SUBSCRIBE_FAIL',
  FACEBOOK_SUBSCRIBE_CANCEL = 'FACEBOOK_SUBSCRIBE_CANCEL',

  FACEBOOK_UNSUBSCRIBE_REQUEST = 'FACEBOOK_UNSUBSCRIBE_REQUEST',
  FACEBOOK_UNSUBSCRIBE_SUCCESS = 'FACEBOOK_UNSUBSCRIBE_SUCCESS',
  FACEBOOK_UNSUBSCRIBE_FAIL = 'FACEBOOK_UNSUBSCRIBE_FAIL',
  FACEBOOK_UNSUBSCRIBE_CANCEL = 'FACEBOOK_UNSUBSCRIBE_CANCEL',

  FACEBOOK_ACTIVE_PAGES_REQUEST = 'FACEBOOK_ACTIVE_PAGES_REQUEST',
  FACEBOOK_ACTIVE_PAGES_SUCCESS = 'FACEBOOK_ACTIVE_PAGES_SUCCESS',
  FACEBOOK_ACTIVE_PAGES_FAIL = 'FACEBOOK_ACTIVE_PAGES_FAIL',
  FACEBOOK_ACTIVE_PAGES_CANCEL = 'FACEBOOK_ACTIVE_PAGES_CANCEL',

  FACEBOOK_UPDATE_PAGE_SETTINGS_REQUEST = 'FACEBOOK_UPDATE_PAGE_SETTINGS_REQUEST',
  FACEBOOK_UPDATE_PAGE_SETTINGS_SUCCESS = 'FACEBOOK_UPDATE_PAGE_SETTINGS_SUCCESS',
  FACEBOOK_UPDATE_PAGE_SETTINGS_FAIL = 'FACEBOOK_UPDATE_PAGE_SETTINGS_FAIL',
  FACEBOOK_UPDATE_PAGE_SETTINGS_CANCEL = 'FACEBOOK_UPDATE_PAGE_SETTINGS_CANCEL',
}

export enum WebhooksActionTypes {
  FETCH_WEBHOOKS_REQUEST = 'FETCH_WEBHOOK_LIST_REQUEST',
  FETCH_WEBHOOKS_SUCCESS = 'FETCH_WEBHOOK_LIST_SUCCESS',
  FETCH_WEBHOOKS_FAIL = 'FETCH_WEBHOOK_LIST_FAIL',

  ADD_WEBHOOK_REQUEST = 'ADD_WEBHOOK_REQUEST',
  ADD_WEBHOOK_SUCCESS = 'ADD_WEBHOOK_SUCCESS',
  ADD_WEBHOOK_FAIL = 'ADD_WEBHOOK_FAIL',

  EDIT_WEBHOOK_REQUEST = 'EDIT_WEBHOOK_REQUEST',
  EDIT_WEBHOOK_SUCCESS = 'EDIT_WEBHOOK_SUCCESS',
  EDIT_WEBHOOK_FAIL = 'EDIT_WEBHOOK_FAIL',

  SEARCH_WEBHOOK_REQUEST = 'SEARCH_WEBHOOK_REQUEST',
  SEARCH_WEBHOOK_SUCCESS = 'SEARCH_WEBHOOK_SUCCESS',
  SEARCH_WEBHOOK_FAIL = 'SEARCH_WEBHOOK_FAIL',

  DELETE_WEBHOOK_REQUEST = 'DELETE_WEBHOOK_REQUEST',
  DELETE_WEBHOOK_SUCCESS = 'DELETE_WEBHOOK_SUCCESS',
  DELETE_WEBHOOK_FAIL = 'DELETE_WEBHOOK_FAIL',

  GET_SIGNATURE_REQUEST = 'GET_SIGNATURE_REQUEST',
  GET_SIGNATURE_SUCCESS = 'GET_SIGNATURE_SUCCESS',
  GET_SIGNATURE_FAIL = 'GET_SIGNATURE_FAIL',
}

export enum TicketFieldsActionTypes {
  FETCH_TICKET_FIELDS_REQUEST = 'FETCH_TICKET_FIELDS_REQUEST',
  FETCH_TICKET_FIELDS_SUCCESS = 'FETCH_TICKET_FIELDS_SUCCESS',
  FETCH_TICKET_FIELDS_FAIL = 'FETCH_TICKET_FIELDS_FAIL',

  CREATE_TICKET_FIELD_REQUEST = 'CREATE_TICKET_FIELD_REQUEST',
  CREATE_TICKET_FIELD_SUCCESS = 'CREATE_TICKET_FIELD_SUCCESS',
  CREATE_TICKET_FIELD_FAIL = 'CREATE_TICKET_FIELD_FAIL',

  UPDATE_TICKET_FIELD_REQUEST = 'UPDATE_TICKET_FIELD_REQUEST',
  UPDATE_TICKET_FIELD_SUCCESS = 'UPDATE_TICKET_FIELD_SUCCESS',
  UPDATE_TICKET_FIELD_FAIL = 'UPDATE_TICKET_FIELD_FAIL',

  DELETE_TICKET_FIELD_REQUEST = 'DELETE_TICKET_FIELD_REQUEST',
  DELETE_TICKET_FIELD_SUCCESS = 'DELETE_TICKET_FIELD_SUCCESS',
  DELETE_TICKET_FIELD_FAIL = 'DELETE_TICKET_FIELD_FAIL',

  GET_TICKET_FIELD_REQUEST = 'GET_TICKET_FIELD_REQUEST',
  GET_TICKET_FIELD_SUCCESS = 'GET_TICKET_FIELD_SUCCESS',
  GET_TICKET_FIELD_FAIL = 'GET_TICKET_FIELD_FAIL',

  ADD_TICKET_FIELD_DATA_REQUEST = 'ADD_TICKET_FIELD_DATA_REQUEST',
  ADD_TICKET_FIELD_DATA_SUCCESS = 'ADD_TICKET_FIELD_DATA_SUCCESS',
  ADD_TICKET_FIELD_DATA_FAIL = 'ADD_TICKET_FIELD_DATA_FAIL',

  GET_TICKET_FIELD_DATA_LIST_REQUEST = 'GET_TICKET_FIELD_DATA_LIST_REQUEST',
  GET_TICKET_FIELD_DATA_LIST_SUCCESS = 'GET_TICKET_FIELD_DATA_LIST_SUCCESS',
  GET_TICKET_FIELD_DATA_LIST_FAIL = 'GET_TICKET_FIELD_DATA_LIST_FAIL',

  UPDATE_TICKET_FIELD_DATA_REQUEST = 'UPDATE_TICKET_FIELD_DATA_REQUEST',
  UPDATE_TICKET_FIELD_DATA_SUCCESS = 'UPDATE_TICKET_FIELD_DATA_SUCCESS',
  UPDATE_TICKET_FIELD_DATA_FAIL = 'UPDATE_TICKET_FIELD_DATA_FAIL',

  CHECK_TICKET_FIELD_KEY_VALIDATION_REQUEST = 'CHECK_TICKET_FIELD_KEY_VALIDATION_REQUEST',
  CHECK_TICKET_FIELD_KEY_VALIDATION_SUCCESS = 'CHECK_TICKET_FIELD_KEY_VALIDATION_SUCCESS',
  CHECK_TICKET_FIELD_KEY_VALIDATION_FAIL = 'CHECK_TICKET_FIELD_KEY_VALIDATION_FAIL',

  SET_CHECKING_STATUS_TICKET_FIELD_KEY_VALIDATION = 'SET_CHECKING_STATUS_TICKET_FIELD_KEY_VALIDATION',
}

export enum CustomerFieldsActionTypes {
  CREATE_CUSTOMER_FIELD_REQUEST = 'CREATE_CUSTOMER_FIELD_REQUEST',
  CREATE_CUSTOMER_FIELD_SUCCESS = 'CREATE_CUSTOMER_FIELD_SUCCESS',
  CREATE_CUSTOMER_FIELD_FAIL = 'CREATE_CUSTOMER_FIELD_FAIL',

  FETCH_CUSTOMER_FIELDS_REQUEST = 'FETCH_CUSTOMER_FIELDS_REQUEST',
  FETCH_CUSTOMER_FIELDS_SUCCESS = 'FETCH_CUSTOMER_FIELDS_SUCCESS',
  FETCH_CUSTOMER_FIELDS_FAIL = 'FETCH_CUSTOMER_FIELDS_FAIL',

  GET_CUSTOMER_FIELD_REQUEST = 'GET_CUSTOMER_FIELD_REQUEST',
  GET_CUSTOMER_FIELD_SUCCESS = 'GET_CUSTOMER_FIELD_SUCCESS',
  GET_CUSTOMER_FIELD_FAIL = 'GET_CUSTOMER_FIELD_FAIL',

  CHECK_CUSTOMER_FIELD_KEY_VALIDATION_REQUEST = 'CHECK_CUSTOMER_FIELD_KEY_VALIDATION_REQUEST',
  CHECK_CUSTOMER_FIELD_KEY_VALIDATION_SUCCESS = 'CHECK_CUSTOMER_FIELD_KEY_VALIDATION_SUCCESS',
  CHECK_CUSTOMER_FIELD_KEY_VALIDATION_FAIL = 'CHECK_CUSTOMER_FIELD_KEY_VALIDATION_FAIL',

  UPDATE_CUSTOMER_FIELD_REQUEST = 'UPDATE_CUSTOMER_FIELD_REQUEST',
  UPDATE_CUSTOMER_FIELD_SUCCESS = 'UPDATE_CUSTOMER_FIELD_SUCCESS',
  UPDATE_CUSTOMER_FIELD_FAIL = 'UPDATE_CUSTOMER_FIELD_FAIL',

  DELETE_CUSTOMER_FIELD_REQUEST = 'DELETE_CUSTOMER_FIELD_REQUEST',
  DELETE_CUSTOMER_FIELD_SUCCESS = 'DELETE_CUSTOMER_FIELD_SUCCESS',
  DELETE_CUSTOMER_FIELD_FAIL = 'DELETE_CUSTOMER_FIELD_FAIL',

  GET_CUSTOMER_FIELD_DATA_LIST_REQUEST = 'GET_CUSTOMER_FIELD_DATA_LIST_REQUEST',
  GET_CUSTOMER_FIELD_DATA_LIST_SUCCESS = 'GET_CUSTOMER_FIELD_DATA_LIST_SUCCESS',
  GET_CUSTOMER_FIELD_DATA_LIST_FAIL = 'GET_CUSTOMER_FIELD_DATA_LIST_FAIL',

  ADD_CUSTOMER_FIELD_DATA_REQUEST = 'ADD_CUSTOMER_FIELD_DATA_REQUEST',
  ADD_CUSTOMER_FIELD_DATA_SUCCESS = 'ADD_CUSTOMER_FIELD_DATA_SUCCESS',
  ADD_CUSTOMER_FIELD_DATA_FAIL = 'ADD_CUSTOMER_FIELD_DATA_FAIL',

  UPDATE_CUSTOMER_FIELD_DATA_REQUEST = 'UPDATE_CUSTOMER_FIELD_DATA_REQUEST',
  UPDATE_CUSTOMER_FIELD_DATA_SUCCESS = 'UPDATE_CUSTOMER_FIELD_DATA_SUCCESS',
  UPDATE_CUSTOMER_FIELD_DATA_FAIL = 'UPDATE_CUSTOMER_FIELD_DATA_FAIL',

  SET_CHECKING_STATUS_CUSTOMER_FIELD_KEY_VALIDATION = 'SET_CHECKING_STATUS_TICKET_FIELD_KEY_VALIDATION',
}

export enum TwitterActionTypes {
  FETCH_TICKET_TWITTER_USER_DETAIL_REQUEST = 'FETCH_TICKET_TWITTER_USER_DETAIL_REQUEST',
  FETCH_TICKET_TWITTER_USER_DETAIL_SUCCESS = 'FETCH_TICKET_TWITTER_USER_DETAIL_SUCCESS',
  FETCH_TICKET_TWITTER_USER_DETAIL_FAIL = 'FETCH_TICKET_TWITTER_USER_DETAIL_FAIL',
  FETCH_TICKET_TWITTER_USER_DETAIL_CANCEL = 'FETCH_TICKET_TWITTER_USER_DETAIL_CANCEL',

  FOLLOW_TWITTER_USER_REQUEST = 'FOLLOW_TWITTER_USER_REQUEST',
  FOLLOW_TWITTER_USER_SUCCESS = 'FOLLOW_TWITTER_USER_SUCCESS',
  FOLLOW_TWITTER_USER_FAIL = 'FOLLOW_TWITTER_USER_FAIL',
  FOLLOW_TWITTER_USER_CANCEL = 'FOLLOW_TWITTER_USER_CANCEL',

  UNFOLLOW_TWITTER_USER_REQUEST = 'UNFOLLOW_TWITTER_USER_REQUEST',
  UNFOLLOW_TWITTER_USER_SUCCESS = 'UNFOLLOW_TWITTER_USER_SUCCESS',
  UNFOLLOW_TWITTER_USER_FAIL = 'UNFOLLOW_TWITTER_USER_FAIL',
  UNFOLLOW_TWITTER_USER_CANCEL = 'UNFOLLOW_TWITTER_USER_CANCEL',
}

export enum ProactiveChatActionTypes {
  GET_PROACTIVE_CHAT_LIST_REQUEST = 'GET_PROACTIVE_CHAT_LIST_REQUEST',
  GET_PROACTIVE_CHAT_LIST_SUCCESS = 'GET_PROACTIVE_CHAT_LIST_SUCCESS',
  GET_PROACTIVE_CHAT_LIST_FAIL = 'GET_PROACTIVE_CHAT_LIST_FAIL',

  GET_PROACTIVE_CHAT_TICKETS_REQUEST = 'GET_PROACTIVE_CHAT_TICKETS_REQUEST',
  GET_PROACTIVE_CHAT_TICKETS_SUCCESS = 'GET_PROACTIVE_CHAT_TICKETS_SUCCESS',
  GET_PROACTIVE_CHAT_TICKETS_FAIL = 'GET_PROACTIVE_CHAT_TICKETS_FAIL',

  CREATE_PROACTIVE_CHAT_REQUEST = 'CREATE_PROACTIVE_CHAT_REQUEST',
  CREATE_PROACTIVE_CHAT_SUCCESS = 'CREATE_PROACTIVE_CHAT_SUCCESS',
  CREATE_PROACTIVE_CHAT_FAIL = 'CREATE_PROACTIVE_CHAT_FAIL',

  SET_PROACTIVE_CHAT_DATE = 'SET_PROACTIVE_CHAT_DATE',
  SET_PROACTIVE_CHAT_QUERY = 'SET_PROACTIVE_CHAT_QUERY',
}
