export enum DialogsActionTypes {
  SHOW_DIALOGS_REQUEST = 'SHOW_DIALOGS_REQUEST',
  SHOW_DIALOGS_SUCCESS = 'SHOW_DIALOGS_SUCCESS',

  HIDE_DIALOGS_REQUEST = 'HIDE_DIALOGS_REQUEST',
  HIDE_DIALOGS_SUCCESS = 'HIDE_DIALOGS_SUCCESS',
}

export enum ImagePreviewActionTypes {
  SHOW_IMAGE_PREVIEW_REQUEST = 'SHOW_IMAGE_PREVIEW_REQUEST',
  HIDE_IMAGE_PREVIEW_REQUEST = 'HIDE_IMAGE_PREVIEW_REQUEST',
}

export enum FilesActionTypes {
  FILE_SAVE_REQUEST = 'FILE_SAVE_REQUEST',
  FILE_SAVE_SUCCESS = 'FILE_SAVE_SUCCESS',
  FILE_SAVE_FAIL = 'FILE_SAVE_FAIL',
}

export enum NotificationsActionTypes {
  ADD_NOTIFICATIONS_REQUEST = 'ADD_NOTIFICATIONS_REQUEST',
  ADD_DESKTOP_NOTIFICATIONS_REQUEST = 'ADD_DESKTOP_NOTIFICATIONS_REQUEST',
}

export enum AlertActionTypes {
  INIT = 'INIT',
  SHOW_ALERT = 'SHOW_ALERT',
  HIDE_ALERT = 'HIDE_ALERT',
}

export enum BillingActionTypes {
  FETCH_CARD_INFO_REQUEST = 'FETCH_CARD_INFO_REQUEST',
  FETCH_CARD_INFO_SUCCESS = 'FETCH_CARD_INFO_SUCCESS',
  FETCH_CARD_INFO_CANCEL = 'FETCH_CARD_INFO_CANCEL',
  FETCH_CARD_INFO_FAIL = 'FETCH_CARD_INFO_FAIL',

  SAVE_BILLING_CONTACTS_REQUEST = 'SAVE_BILLING_CONTACTS_REQUEST',
  SAVE_BILLING_CONTACTS_SUCCESS = 'SAVE_BILLING_CONTACTS_SUCCESS',
  SAVE_BILLING_CONTACTS_CANCEL = 'SAVE_BILLING_CONTACTS_CANCEL',
  SAVE_BILLING_CONTACTS_FAIL = 'SAVE_BILLING_CONTACTS_FAIL',
}

// account
export enum AccountActionTypes {
  CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL',

  CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST',
  CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS',
  CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL',

  UNREGISTER_REQUEST = 'UNREGISTER_REQUEST',
  UNREGISTER_SUCCESS = 'UNREGISTER_SUCCESS',
  UNREGISTER_FAIL = 'UNREGISTER_FAIL',

  IS_ABLE_TO_UNREGISTER_REQUEST = 'IS_ABLE_TO_UNREGISTER_REQUEST',
  IS_ABLE_TO_UNREGISTER_SUCCESS = 'IS_ABLE_TO_UNREGISTER_SUCCESS',
  IS_ABLE_TO_UNREGISTER_FAIL = 'IS_ABLE_TO_UNREGISTER_FAIL',

  TURNOFF_GOOGLE_AUTHENTICATOR_REQUEST = 'TURNOFF_GOOGLE_AUTHENTICATOR_REQUEST',
  TURNOFF_GOOGLE_AUTHENTICATOR_SUCCESS = 'TURNOFF_GOOGLE_AUTHENTICATOR_SUCCESS',
  TURNOFF_GOOGLE_AUTHENTICATOR_FAIL = 'TURNOFF_GOOGLE_AUTHENTICATOR_FAIL',

  UPDATE_USER = 'UPDATE_USER',
}

// authentication
export enum AuthenticationActionTypes {
  SIGNIN_REQUEST = 'SIGNIN_REQUEST',
  SIGNIN_SUCCESS = 'SIGNIN_SUCCESS',
  SIGNIN_FAIL = 'SIGNIN_FAIL',

  SAML_SIGNIN_INITIATE_REQUEST = 'SAML_SIGNIN_INITIATE_REQUEST',
  SAML_SIGNIN_INITIATE_SUCCESS = 'SAML_SIGNIN_INITIATE_SUCCESS',
  SAML_SIGNIN_INITIATE_FAIL = 'SAML_SIGNIN_INITIATE_FAIL',
  SAML_SIGNIN_INITIATE_RESET = 'SAML_SIGNIN_INITIATE_RESET',

  RESEND_ACTIVATION_MAIL = 'RESEND_ACTIVATION_MAIL',

  SIGNUP_REQUEST = 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
  SIGNUP_FAIL = 'SIGNUP_FAIL',

  VERIFY_AUTHENTICATION_REQUEST = 'VERIFY_AUTHENTICATION_REQUEST',
  VERIFY_AUTHENTICATION_SUCCESS = 'VERIFY_AUTHENTICATION_SUCCESS',
  VERIFY_AUTHENTICATION_FAIL = 'VERIFY_AUTHENTICATION_FAIL',

  VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL',

  CONFIRM_EMAIL_CHANGE_REQUEST = 'CONFIRM_EMAIL_CHANGE_REQUEST',
  CONFIRM_EMAIL_CHANGE_SUCCESS = 'CONFIRM_EMAIL_CHANGE_SUCCESS',
  CONFIRM_EMAIL_CHANGE_FAIL = 'CONFIRM_EMAIL_CHANGE_FAIL',

  SEND_EMAIL_VERIFICATION_MAIL_REQUEST = 'SEND_EMAIL_VERIFICATION_MAIL_REQUEST',
  SEND_EMAIL_VERIFICATION_MAIL_SUCCESS = 'SEND_EMAIL_VERIFICATION_MAIL_SUCCESS',
  SEND_EMAIL_VERIFICATION_MAIL_FAIL = 'SEND_EMAIL_VERIFICATION_MAIL_FAIL',

  AUTHENTICATED = 'AUTHENTICATED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL',

  SIGNOUT_REQUEST = 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS',

  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL',

  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL',

  FETCH_INVITATION_REQUEST = 'FETCH_INVITATION_REQUEST',
  FETCH_INVITATION_SUCCESS = 'FETCH_INVITATION_SUCCESS',
  FETCH_INVITATION_FAIL = 'FETCH_INVITATION_FAIL',

  OAUTH_GOOGLE_REQUEST = 'OAUTH_GOOGLE_REQUEST',
  OAUTH_GOOGLE_FAIL = 'OAUTH_GOOGLE_FAIL',

  SET_TWO_FACTOR_AUTHENTICATION = 'SET_TWO_FACTOR_AUTHENTICATION',

  RECOVER_TWO_FACTOR_AUTHENTICATION_REQUEST = 'RECOVER_TWO_FACTOR_AUTHENTICATION_REQUEST',
  RECOVER_TWO_FACTOR_AUTHENTICATION_SUCCESS = 'RECOVER_TWO_FACTOR_AUTHENTICATION_SUCCESS',
  RECOVER_TWO_FACTOR_AUTHENTICATION_FAIL = 'RECOVER_TWO_FACTOR_AUTHENTICATION_FAIL',

  PROVE_GREEN_LANTERN_REQUEST = 'PROVE_GREEN_LANTERN_REQUEST',
  PROVE_GREEN_LANTERN_SUCCESS = 'PROVE_GREEN_LANTERN_SUCCESS',
  PROVE_GREEN_LANTERN_FAIL = 'PROVE_GREEN_LANTERN_FAIL',
}

export enum OrganizationsActionTypes {
  CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS',

  UPDATE_ORGANIZATION_REQUEST = 'UPDATE_ORGANIZATION_REQUEST',
  UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS',
  UPDATE_ORGANIZATION_FAIL = 'UPDATE_ORGANIZATION_FAIL',

  UPDATE_ORGANIZATION_NAME_REQUEST = 'UPDATE_ORGANIZATION_NAME_REQUEST',
  UPDATE_ORGANIZATION_NAME_SUCCESS = 'UPDATE_ORGANIZATION_NAME_SUCCESS',
  UPDATE_ORGANIZATION_NAME_FAIL = 'UPDATE_ORGANIZATION_NAME_FAIL',
  UPDATE_ORGANIZATION_NAME_RESET = 'RESET_UPDATE_ORGANIZATION_NAME',

  UPDATE_SAML_CONFIGURATION_AND_SLUG_NAME_REQUEST = 'UPDATE_SAML_CONFIGURATION_AND_SLUG_NAME_REQUEST',
  UPDATE_ORGANIZATION_SLUG_NAME_SUCCESS = 'UPDATE_ORGANIZATION_SLUG_NAME_SUCCESS',
  UPDATE_ORGANIZATION_SLUG_NAME_FAIL = 'UPDATE_ORGANIZATION_SLUG_NAME_FAIL',
  UPDATE_ORGANIZATION_SLUG_NAME_RESET = 'UPDATE_ORGANIZATION_SLUG_NAME_RESET',

  DELETE_ORGANIZATION_MEMBERS_REQUEST = 'DELETE_ORGANIZATION_MEMBERS_REQUEST',
  DELETE_ORGANIZATION_MEMBERS_SUCCESS = 'DELETE_ORGANIZATION_MEMBERS_SUCCESS',
  DELETE_ORGANIZATION_MEMBERS_FAIL = 'DELETE_ORGANIZATION_MEMBERS_FAIL',

  UPDATE_ORGANIZATION_MEMBER_ROLE_REQUEST = 'UPDATE_ORGANIZATION_MEMBER_ROLE_REQUEST',
  UPDATE_ORGANIZATION_MEMBER_ROLE_SUCCESS = 'UPDATE_ORGANIZATION_MEMBER_ROLE_SUCCESS',
  UPDATE_ORGANIZATION_MEMBER_ROLE_FAIL = 'UPDATE_ORGANIZATION_MEMBER_ROLE_FAIL',

  INVITE_MEMBER_REQUEST = 'INVITE_MEMBER_REQUEST',
  INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS',
  INVITE_MEMBER_FAIL = 'INVITE_MEMBER_FAIL',

  UPDATE_INVITATION_REQUEST = 'UPDATE_INVITATION_REQUEST',
  UPDATE_INVITATION_SUCCESS = 'UPDATE_INVITATION_SUCCESS',
  UPDATE_INVITATION_FAIL = 'UPDATE_INVITATION_FAIL',

  CANCEL_INVITATION_REQUEST = 'CANCEL_INVITATION_REQUEST',
  CANCEL_INVITATION_SUCCESS = 'CANCEL_INVITATION_SUCCESS',
  CANCEL_INVITATION_FAIL = 'CANCEL_INVITATION_FAIL',

  UPDATE_SAML_CONFIGURATION_REQUEST = 'UPDATE_SAML_CONFIGURATION_REQUEST',
  UPDATE_SAML_CONFIGURATION_SUCCESS = 'UPDATE_SAML_CONFIGURATION_SUCCESS',
  UPDATE_SAML_CONFIGURATION_FAIL = 'UPDATE_SAML_CONFIGURATION_FAIL',
  UPDATE_SAML_CONFIGURATION_RESET = 'UPDATE_SAML_CONFIGURATION_RESET',

  DELETE_SAML_CONFIGURATION_REQUEST = 'DELETE_SAML_CONFIGURATION_REQUEST',

  TRANSFER_OWNER_REQUEST = 'TRANSFER_OWNER_REQUEST',
  TRANSFER_OWNER_SUCCESS = 'TRANSFER_OWNER_SUCCESS',
  TRANSFER_OWNER_FAIL = 'TRANSFER_OWNER_FAIL',

  EXPORT_MEMBERS_REQUEST = 'EXPORT_MEMBERS_REQUEST',
  EXPORT_MEMBERS_SUCCESS = 'EXPORT_MEMBERS_SUCCESS',
}

export enum SendBirdActionTypes {
  SB_CONNECT_REQUEST = 'SB_CONNECT_REQUEST',
  SB_CONNECT_SUCCESS = 'SB_CONNECT_SUCCESS',
  SB_CONNECT_FAIL = 'SB_CONNECT_FAIL',

  SB_RECONNECT_REQUEST = 'SB_RECONNECT_REQUEST',
  SB_RECONNECT_SUCCESS = 'SB_RECONNECT_SUCCESS',
  SB_RECONNECT_FAIL = 'SB_RECONNECT_FAIL',

  SB_DISCONNECT_REQUEST = 'SB_DISCONNECT_REQUEST',
  SB_DISCONNECT_SUCCESS = 'SB_DISCONNECT_SUCCESS',
  SB_DISCONNECT_FAIL = 'SB_DISCONNECT_FAIL',
}

export enum SearchActionTypes {
  FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST',
  FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL',
  FETCH_SEARCH_CANCEL = 'FETCH_SEARCH_CANCEL',
  RESET_SEARCH = 'RESET_SEARCH',

  INIT_SEARCH_CUSTOM_DATA_REQUEST = 'INIT_SEARCH_CUSTOM_DATA_REQUEST',
  INIT_SEARCH_CUSTOM_DATA_SUCCESS = 'INIT_SEARCH_CUSTOM_DATA_SUCCESS',
  INIT_SEARCH_CUSTOM_DATA_FAIL = 'INIT_SEARCH_CUSTOM_DATA_FAIL',

  SET_SEARCH_MODE = 'SET_SEARCH_MODE',

  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SEARCH_SAVED_PARAMETERS = 'SET_SEARCH_SAVED_PARAMETERS',
}

export enum IntlActionTypes {
  SELECT_LOCALE = 'SELECT_LOCALE',
  TOGGLE_INSPECTOR = 'TOGGLE_INSPECTOR',
  TOGGLE_KEY_OVERLAY_MODE = 'TOGGLE_KEY_OVERLAY_MODE',
}

export enum LNBActionTypes {
  SET_LNB_MENU_ITEMS = 'SET_LNB_MENU_ITEMS',
  SET_ACTIVE_LNB_MENU_ITEM = 'SET_ACTIVE_LNB_MENU_ITEM',
  UPDATE_LNB_MENU_ITEM = 'UPDATE_LNB_MENU_ITEM',
}
