export enum ApplicationActionTypes {
  FETCH_APPLICATION_REQUEST = 'FETCH_APPLICATION_REQUEST',
  FETCH_APPLICATION_SUCCESS = 'FETCH_APPLICATION_SUCCESS',
  FETCH_APPLICATION_FAIL = 'FETCH_APPLICATION_FAIL',
  FETCH_APPLICATION_CANCEL = 'FETCH_APPLICATION_CANCEL',

  SET_APPLICATION_REQUEST = 'SET_APPLICATION_REQUEST',
  UPDATE_APPLICATION_ATTRIBUTES = 'UPDATE_APPLICATION_ATTRIBUTES',

  RESET_APPLICATION_REQUEST = 'RESET_APPLICATION_REQUEST',
  RESET_APPLICATION_SUCCESS = 'RESET_APPLICATION_SUCCESS',

  RESET_APPLICATIONS_REQUEST = 'RESET_APPLICATIONS_REQUEST',

  CREATE_APP_REQUEST = 'CREATE_APP_REQUEST',
  CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS',
  CREATE_APP_FAIL = 'CREATE_APP_FAIL',

  CHANGE_APP_NAME_REQUEST = 'CHANGE_APP_NAME_REQUEST',
  CHANGE_APP_NAME_SUCCESS = 'CHANGE_APP_NAME_SUCCESS',
  CHANGE_APP_NAME_FAIL = 'CHANGE_APP_NAME_FAIL',

  CHANGE_APPLICATION_REQUEST = 'CHANGE_APPLICATION_REQUEST',

  GET_API_TOKEN_REQUEST = 'GET_API_TOKEN_REQUEST',
  GET_API_TOKEN_SUCCESS = 'GET_API_TOKEN_SUCCESS',
  GET_API_TOKEN_FAIL = 'GET_API_TOKEN_FAIL',

  REGISTER_CALLS_APPLICATION = 'REGISTER_CALLS_APPLICATION',
}

export enum OverviewActionTypes {
  FETCH_MAU_REQUEST = 'FETCH_MAU_REQUEST',
  FETCH_MAU_SUCCESS = 'FETCH_MAU_SUCCESS',
  FETCH_MAU_FAIL = 'FETCH_MAU_FAIL',
  FETCH_MAU_CANCEL = 'FETCH_MAU_CANCEL',

  FETCH_DAU_REQUEST = 'FETCH_DAU_REQUEST',
  FETCH_DAU_SUCCESS = 'FETCH_DAU_SUCCESS',
  FETCH_DAU_FAIL = 'FETCH_DAU_FAIL',
  FETCH_DAU_CANCEL = 'FETCH_DAU_CANCEL',

  FETCH_MESSAGES_COUNT_REQUEST = 'FETCH_MESSAGES_COUNT_REQUEST',
  FETCH_MESSAGES_COUNT_SUCCESS = 'FETCH_MESSAGES_COUNT_SUCCESS',
  FETCH_MESSAGES_COUNT_FAIL = 'FETCH_MESSAGES_COUNT_FAIL',
  FETCH_MESSAGES_COUNT_CANCEL = 'FETCH_MESSAGES_COUNT_CANCEL',

  FETCH_MONTHLY_CCU_REQUEST = 'FETCH_MONTHLY_CCU_REQUEST',
  FETCH_MONTHLY_CCU_SUCCESS = 'FETCH_MONTHLY_CCU_SUCCESS',
  FETCH_MONTHLY_CCU_FAIL = 'FETCH_MONTHLY_CCU_FAIL',
  FETCH_MONTHLY_CCU_CANCEL = 'FETCH_MONTHLY_CCU_CANCEL',

  FETCH_DAILY_CCU_REQUEST = 'FETCH_DAILY_CCU_REQUEST',
  FETCH_DAILY_CCU_SUCCESS = 'FETCH_DAILY_CCU_SUCCESS',
  FETCH_DAILY_CCU_FAIL = 'FETCH_DAILY_CCU_FAIL',
  FETCH_DAILY_CCU_CANCEL = 'FETCH_DAILY_CCU_CANCEL',

  FETCH_HOURLY_CCU_REQUEST = 'FETCH_HOURLY_CCU_REQUEST',
  FETCH_HOURLY_CCU_SUCCESS = 'FETCH_HOURLY_CCU_SUCCESS',
  FETCH_HOURLY_CCU_FAIL = 'FETCH_HOURLY_CCU_FAIL',
  FETCH_HOURLY_CCU_CANCEL = 'FETCH_HOURLY_CCU_CANCEL',
}

export enum SDKUserActionTypes {
  FETCH_SDK_USER_REQUEST = 'FETCH_SDK_USER_REQUEST',
  FETCH_SDK_USER_SUCCESS = 'FETCH_SDK_USER_SUCCESS',
  FETCH_SDK_USER_CANCEL = 'FETCH_SDK_USER_CANCEL',
  FETCH_SDK_USER_FAIL = 'FETCH_SDK_USER_FAIL',

  CREATE_SDK_USER_REQUEST = 'CREATE_SDK_USER_REQUEST',
  CREATE_SDK_USER_SUCCESS = 'CREATE_SDK_USER_SUCCESS',
  CREATE_SDK_USER_CANCEL = 'CREATE_SDK_USER_CANCEL',
  CREATE_SDK_USER_FAIL = 'CREATE_SDK_USER_FAIL',

  UPDATE_SDK_USER_REQUEST = 'UPDATE_SDK_USER_REQUEST',
  UPDATE_SDK_USER_SUCCESS = 'UPDATE_SDK_USER_SUCCESS',
  UPDATE_SDK_USER_CANCEL = 'UPDATE_SDK_USER_CANCEL',
  UPDATE_SDK_USER_FAIL = 'UPDATE_SDK_USER_FAIL',

  REMOVE_SDK_USER_REQUEST = 'REMOVE_SDK_USER_REQUEST',
  REMOVE_SDK_USER_SUCCESS = 'REMOVE_SDK_USER_SUCCESS',
  REMOVE_SDK_USER_FAIL = 'REMOVE_SDK_USER_FAIL',
}

export enum SettingsActionTypes {
  TOGGLE_PUSH_ENABLED_REQUEST = 'TOGGLE_PUSH_ENABLED_REQUEST',
  TOGGLE_PUSH_ENABLED_SUCCESS = 'TOGGLE_PUSH_ENABLED_SUCCESS',
  TOGGLE_PUSH_ENABLED_FAIL = 'TOGGLE_PUSH_ENABLED_FAIL',

  // push message templates
  FETCH_PUSH_MESSAGE_TEMPLATES_REQUEST = 'FETCH_PUSH_MESSAGE_TEMPLATES_REQUEST',
  FETCH_PUSH_MESSAGE_TEMPLATES_SUCCESS = 'FETCH_PUSH_MESSAGE_TEMPLATES_SUCCESS',
  FETCH_PUSH_MESSAGE_TEMPLATES_FAIL = 'FETCH_PUSH_MESSAGE_TEMPLATES_FAIL',

  UPDATE_PUSH_MESSAGE_TEMPLATES_REQUEST = 'UPDATE_PUSH_MESSAGE_TEMPLATES_REQUEST',
  UPDATE_PUSH_MESSAGE_TEMPLATES_SUCCESS = 'UPDATE_PUSH_MESSAGE_TEMPLATES_SUCCESS',
  UPDATE_PUSH_MESSAGE_TEMPLATES_FAIL = 'UPDATE_PUSH_MESSAGE_TEMPLATES_FAIL',

  UPDATE_FILE_MESSAGE_EVENT_REQUEST = 'UPDATE_FILE_MESSAGE_EVENT_REQUEST',
  UPDATE_FILE_MESSAGE_EVENT_SUCCESS = 'UPDATE_FILE_MESSAGE_EVENT_SUCCESS',
  UPDATE_FILE_MESSAGE_EVENT_FAIL = 'UPDATE_FILE_MESSAGE_EVENT_FAIL',

  GET_WEBHOOKS_ALL_CATEGORIES_REQUEST = 'GET_WEBHOOKS_ALL_CATEGORIES_REQUEST',
  GET_WEBHOOKS_ALL_CATEGORIES_SUCCESS = 'GET_WEBHOOKS_ALL_CATEGORIES_SUCCESS',
  GET_WEBHOOKS_ALL_CATEGORIES_FAIL = 'GET_WEBHOOKS_ALL_CATEGORIES_FAIL',

  GET_WEBHOOKS_INFORMATION_REQUEST = 'GET_WEBHOOKS_INFORMATION_REQUEST',
  GET_WEBHOOKS_INFORMATION_SUCCESS = 'GET_WEBHOOKS_INFORMATION_SUCCESS',
  GET_WEBHOOKS_INFORMATION_FAIL = 'GET_WEBHOOKS_INFORMATION_FAIL',

  UPDATE_WEBHOOK_INFORMATION_REQUEST = 'UPDATE_WEBHOOK_INFORMATION_REQUEST',
  UPDATE_WEBHOOK_INFORMATION_SUCCESS = 'UPDATE_WEBHOOK_INFORMATION_SUCCESS',
  UPDATE_WEBHOOK_INFORMATION_FAIL = 'UPDATE_WEBHOOK_INFORMATION_FAIL',

  UPDATE_MAX_LENGTH_MESSAGE_REQUEST = 'UPDATE_MAX_LENGTH_MESSAGE_REQUEST',
  UPDATE_MAX_LENGTH_MESSAGE_SUCCESS = 'UPDATE_MAX_LENGTH_MESSAGE_SUCCESS',
  UPDATE_MAX_LENGTH_MESSAGE_FAIL = 'UPDATE_MAX_LENGTH_MESSAGE_FAIL',

  UPDATE_IGNORE_MESSAGE_OFFSET_REQUEST = 'UPDATE_IGNORE_MESSAGE_OFFSET_REQUEST',
  UPDATE_IGNORE_MESSAGE_OFFSET_SUCCESS = 'UPDATE_IGNORE_MESSAGE_OFFSET_SUCCESS',
  UPDATE_IGNORE_MESSAGE_OFFSET_FAIL = 'UPDATE_IGNORE_MESSAGE_OFFSET_FAIL',

  UPDATE_AUTO_EVENT_MESSAGE_REQUEST = 'UPDATE_AUTO_EVENT_MESSAGE_REQUEST',
  UPDATE_AUTO_EVENT_MESSAGE_SUCCESS = 'UPDATE_AUTO_EVENT_MESSAGE_SUCCESS',
  UPDATE_AUTO_EVENT_MESSAGE_FAIL = 'UPDATE_AUTO_EVENT_MESSAGE_FAIL',

  UPDATE_ACCESS_TOKEN_USER_POLICY_REQUEST = 'UPDATE_ACCESS_TOKEN_USER_POLICY_REQUEST',
  UPDATE_ACCESS_TOKEN_USER_POLICY_SUCCESS = 'UPDATE_ACCESS_TOKEN_USER_POLICY_SUCCESS',
  UPDATE_ACCESS_TOKEN_USER_POLICY_FAIL = 'UPDATE_ACCESS_TOKEN_USER_POLICY_FAIL',

  ADD_CREDENTIALS_FILTER_REQUEST = 'ADD_CREDENTIALS_FILTER_REQUEST',
  ADD_CREDENTIALS_FILTER_SUCCESS = 'ADD_CREDENTIALS_FILTER_SUCCESS',
  ADD_CREDENTIALS_FILTER_FAIL = 'ADD_CREDENTIALS_FILTER_FAIL',

  REMOVE_CREDENTIALS_FILTER_REQUEST = 'REMOVE_CREDENTIALS_FILTER_REQUEST',
  REMOVE_CREDENTIALS_FILTER_SUCCESS = 'REMOVE_CREDENTIALS_FILTER_SUCCESS',
  REMOVE_CREDENTIALS_FILTER_FAIL = 'REMOVE_CREDENTIALS_FILTER_FAIL',

  DELETE_APPLICATION_REQUEST = 'DELETE_APPLICATION_REQUEST',
  DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS',
  DELETE_APPLICATION_FAIL = 'DELETE_APPLICATION_FAIL',

  PUSH_APNS_REGISTER_REQUEST = 'PUSH_APNS_REGISTER_REQUEST',
  PUSH_APNS_REGISTER_SUCCESS = 'PUSH_APNS_REGISTER_SUCCESS',
  PUSH_APNS_REGISTER_FAIL = 'PUSH_APNS_REGISTER_FAIL',

  PUSH_FCM_REGISTER_REQUEST = 'PUSH_FCM_REGISTER_REQUEST',
  PUSH_FCM_REGISTER_SUCCESS = 'PUSH_FCM_REGISTER_SUCCESS',
  PUSH_FCM_REGISTER_FAIL = 'PUSH_FCM_REGISTER_FAIL',

  DELETE_PUSH_CONFIGURATION_REQUEST = 'DELETE_PUSH_CONFIGURATION_REQUEST',
  DELETE_PUSH_CONFIGURATION_SUCCESS = 'DELETE_PUSH_CONFIGURATION_SUCCESS',
  DELETE_PUSH_CONFIGURATION_FAIL = 'DELETE_PUSH_CONFIGURATION_FAIL',

  FETCH_MODERATOR_INFO_ADMM_REQUEST = 'FETCH_MODERATOR_INFO_ADMM_REQUEST',
  FETCH_MODERATOR_INFO_ADMM_SUCCESS = 'FETCH_MODERATOR_INFO_ADMM_SUCCESS',
  FETCH_MODERATOR_INFO_ADMM_FAIL = 'FETCH_MODERATOR_INFO_ADMM_FAIL',

  UPDATE_MODERATOR_INFO_ADMM_REQUEST = 'UPDATE_MODERATOR_INFO_ADMM_REQUEST',
  UPDATE_MODERATOR_INFO_ADMM_SUCCESS = 'UPDATE_MODERATOR_INFO_ADMM_SUCCESS',
  UPDATE_MODERATOR_INFO_ADMM_FAIL = 'UPDATE_MODERATOR_INFO_ADMM_FAIL',
}
